config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root to: 'pages#welcome'
  get '/portfolio', to: 'pages#portfolio'
  root to: 'pages#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def welcome
	end

	def portfolio
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>My Portfolio</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,500,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('https://res.cloudinary.com/dovu27lye/image/upload/v1584176510/portfolio/cyclist_woj1zt.png') %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'  %>
    <%= yield %>
    <%= render 'shared/footer'  %>
  </body>
</html>

app/views/pages/portfolio.html.erb
<div class="page-portfolio">
	<div class="main">
		
	</div>
</div>

app/views/pages/welcome.html.erb
<div class="page-home">	
	<div class="main">
		<div class="main-text">
			<h1>Hello. My name is Sarah and I have creative ideas</h1>
			<div class="btn btn-outline-light">View My Work</div>
		</div>
	</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <div></div>
    <a href="#"><i class="far fa-paper-plane"></i></a>
    <a href="#" target="_blank"><img src="https://res.cloudinary.com/dovu27lye/image/upload/v1583853815/portfolio/cv_cgapyh.png" id="cv-img"/></a>
    <a href="#" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <small class="">
      <div>&copy;
        2020
        Sarah Rhee. All Rights Reserved.
      </div>
      <div>Designed &amp; Developed by
        <a href="https://www.delage.dev/" target="_blank">
        delage.dev</a>
    </small>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="header"> 
	<div class="menu">
		<%= link_to('Welcome', root_path) %>
		<%= link_to('Portfolio', portfolio_path) %>
		<%= link_to('Blog', root_path) %>
		<%= link_to('About', root_path) %>
		<%= link_to('Contact', root_path) %>
	</div>
	<div class="name">
		<%= link_to('Sarah Rhee', root_path) %>
	</div>
</div>